export const usaStates = [
	'Alabama',
	'Alaska',
	'Arizona',
	'Arkansas',
	'California',
	'Colorado',
	'Connecticut',
	'Delaware',
	'Florida',
	'Georgia',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine',
	'Maryland',
	'Massachusetts',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'New Hampshire',
	'New Jersey',
	'New Mexico',
	'New York',
	'North Carolina',
	'North Dakota',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'Rhode Island',
	'South Carolina',
	'South Dakota',
	'Tennessee',
	'Texas',
	'Utah',
	'Vermont',
	'Virginia',
	'Washington',
	'West Virginia',
	'Wisconsin',
	'Wyoming',
];

export const shortenedStates = [
	'AK;CO;CA;ID;MT;NV;OR;UT;WA;WY;AZ;NM;OK;TX;IL;IN;IA;KS;MI;MN;MO;NE;ND;OH;SD;WI;AL;AR;FL;GA;KY;LA;MS;NC;SC;TN;VA;WV;DE;MD;NJ;NY;PA;DC;CT;ME;MA;NH;RI;VT;AB;BC;MB;NB;NF;NT;NS;NU;ON;PE;QC;SK;YT;',
];
